### ISSUE TITLE
iOS 10 support

### ISSUE THREAD

**Issue by TonyVie** [omaralbeik/Drops#14]
Hi would it be possible to lower min iOS target to iOS10 ?
Thanks !

**Comment by omaralbeik** [comment]
I don't see why not, I'm using safe area in the following two places

https://github.com/omaralbeik/Drops/blob/24794231eeafc8b30f8ea7189e3946e34c4385a5/Sources/DropView.swift#L98

https://github.com/omaralbeik/Drops/blob/24794231eeafc8b30f8ea7189e3946e34c4385a5/Sources/Animator.swift#L74

@TonyVie I can open a PR updating those with an `if #available(iOS 11.0, *)` condition, unless you want to of course 😉

**Comment by TonyVie** [comment]
Hi Omar!

I first forgot to thank you for your work ;)

About doing a PR: I'm not comfortable with porting safeAreaLayoutGuide, because I'm stuck with iOS10 on my app: /

**Comment by TonyVie** [comment]
Thanks ! :)
