### ISSUE TITLE
Present `Drop`s "everywhere"

### ISSUE THREAD

**Issue by sbertix** [omaralbeik/Drops#16]
Hey @omaralbeik, 

is there any plan atm for supporting presenting `DropView`s at any level of the view hierarchy? 
I feel like it would make a lot of sense to decouple the actual presentation from the all `WindowViewController` "magic", especially for a better **SwiftUI** support, as it would allow to use `Drop`s in a declarative way. 

```swift
/// An optional `Drop` binding.
@State var drop: Drop?

// Something along the lines of…
var body: some View {
   Text("A random text")
      .frame(maxWidth: .infinity, maxHeight: .infinity)
      .drop($drop)
}
```

With a definition allowing for a `Drops` parameter, so that it could still reuse the same code, or even better, imho, just considering `delayBetweenDrops` (as the whole `Binding` thing would most likely deprecate the current queue system), or nothing at all (letting **SwiftUI** `animation` deal with that). 

```swift
public extension View {
   /// Present a `Drop` view.
   ///
   /// - parameters:
   ///   - drop: An optional `Drop` binding. 
   ///   - drops: Some valid `Drops`. Defaults to `.shared`.
   /// - returns: Some `View`.
   drop(_ drop: Binding<Drop?>, with drops: Drops = .shared) -> some View {
      […]
   }

   // … OR …

   /// Present a `Drop` view.
   ///
   /// - parameters:
   ///   - drop: An optional `Drop` binding. 
   ///   - delayBetweenDrops: Some valid `TimeInterval`. Defaults to `0.5`.
   /// - returns: Some `View`.
   drop(_ drop: Binding<Drop?>, delayedBy delayBetweenDrops: TimeInterval = 0.5) -> some View {
      […]
   }
}
```

Of course this would require `Drop` to at least conform to `Identifiable` (either directly — unlikely due to the current deployment target, or just as an analogy), which would also give the user the ability to cancel _any_ queued presenter "for free", using the imperative `Drops` (when dealing with **UIKit** directly).

```swift
/// Hide some drops.
/// - Parameter drops: `Drop`s to hide.
/// - Note: 
///    This is really just some "concept code". 
///    I tried to make it efficient instead of concise, 
///    but it's very much a draft.
public func hide<C: Collection>(_ drops: C) where C.Element == Drop {
    var identifiers = Set(drops.map(\.id))
    var shouldHideCurrent = false
    dispatchQueue.sync {
        queue.removeAll {
            let isRemoving = identifiers.remove($0.drop.id) != nil
            if !shouldHideCurrent { shouldHideCurrent = isRemoving && current?.drop.id == $0.drop.id }
            return isRemoving
        }
        guard shouldHideCurrent else { return }
        hideCurrent()
    }
}
```

**Comment by omaralbeik** [comment]
Thanks @sbertix, I have the following concerns:
1. This is a **µFramework**, I don't have huge plans for it in the future, I don't want to end up creating a very flexible customizable alerts library, thats why [SwiftMessages](https://github.com/SwiftKickMobile/SwiftMessages/) and other alerts libraries exists.
2. As for now, the majority of apps are still written in UIKit, I want to keep supporting it for a while.

But it might be actually nice to start another project for creating similar alerts in SwiftUI only, that would be very cool!

**Comment by sbertix** [comment]
You're right, no point in making the library heavier. 

I've written a [quick **SwiftUI** implementation](https://github.com/sbertix/DropView), heavily inspired from your work here, just to achieve that. 
Thanks again :muscle:
