### ISSUE TITLE
Xcode 13: 'shared' is unavailable in application extensions for iOS

### ISSUE THREAD

**Issue by fourbytes** [omaralbeik/Drops#20]
Due to a change in the latest Xcode beta, this no longer compiles as a SwiftPM dependency, even for a target that is not an extension.
https://forums.swift.org/t/set-application-extension-api-only-on-a-spm-package/39333/8

It appears `@available(iOSApplicationExtension, unavailable)` now needs to be added in `WindowViewController:44`.

## Error
`SourcePackages/checkouts/Drops/Sources/WindowViewController.swift:44:45: 'shared' is unavailable in application extensions for iOS: Use view controller based solutions where appropriate instead.`

**Comment by saroar** [comment]
@fourbytes have you fixed it ?

**Comment by fourbytes** [comment]
Found a temporary workaround is to use CocoaPods instead of SwiftPM.

**Comment by omaralbeik** [comment]
@fourbytes thanks for reporting this, would you like to open a pull request to fix the issue?

**Comment by omaralbeik** [comment]
Thanks for reporting, should have been fixed in v1.3.0
