### ISSUE TITLE
UI Configuration

### ISSUE THREAD

**Issue by thierrybucco** [omaralbeik/Drops#27]
It would be nice to be able to change Drop UI. Like background color, text color, text size, ...
Do you plan to add this feature?

**Comment by omaralbeik** [comment]
This library was never intended to provide the most extensive way for showing alerts! we're trying to mimic what Apple does in their quick alerts.

Please consider other libraries like [SwiftMessages](https://github.com/SwiftKickMobile/SwiftMessages) if your use case require custom UI.
