### ISSUE TITLE
Unusual layout in iPad split screen mode

### ISSUE THREAD

**Issue by Lightning-Lion** [omaralbeik/Drops#31]
Change `window?.frame = UIScreen.main.bounds` to `window?.frame = UIApplication.shared.keyWindow!.bounds`

**Comment by omaralbeik** [comment]
@Lightning-Lion I'm not sure I understand what you mean here, could you please elaborate more or share a screenshot at least

![Simulator Screen Shot - iPad (9th generation) - 2022-02-03 at 16 33 29](https://user-images.githubusercontent.com/8127757/152374669-afdd2739-494e-460f-a33f-e17094f2d4dc.png)
![Simulator Screen Shot - iPad (9th generation) - 2022-02-03 at 16 33 58](https://user-images.githubusercontent.com/8127757/152374675-b425a24a-296e-42dc-a536-bca04a11252a.png)
![Simulator Screen Shot - iPad (9th generation) - 2022-02-03 at 16 34 08](https://user-images.githubusercontent.com/8127757/152374677-ab508445-628c-4a52-a029-1c049a079a87.png)
