### ISSUE TITLE
Unable to see large text 

### ISSUE THREAD

**Issue by rahulvermaJW** [omaralbeik/Drops#32]
When subtitle is long text the text size is too small that it is unable to be seen, when text is large drop size should be increased instead of decreasing the font size please check this.
![uploadingImage](https://user-images.githubusercontent.com/95697540/152153276-832b50fd-ddea-4455-9e20-8e080b378392.jpg)

**Comment by omaralbeik** [comment]
@rahulvermaJW The drop view uses 1 line labels for both title and subtitle by default, this can be changed by setting `titleNumberOfLines` and `subtitleNumberOfLines` to zero as [explained in the documentation](https://omaralbeik.github.io/Drops/Drop/)

```swift
let drop = Drop(
    title: "Some title",
    titleNumberOfLines: 0,
    subtitle: "Some subtitle",
    subtitleNumberOfLines: 0
)

Drops.show(drop)
```
