### ISSUE TITLE
Customisation

### ISSUE THREAD

**Issue by danipralea** [omaralbeik/Drops#33]
Hello and thank you for creating this!
Is it possible for further customisation? Eg. using it for error messages (think on having a red background color etc)

**Comment by omaralbeik** [comment]
Hi @danipralea 

This library was never intended to provide the most extensive way for showing alerts! we're trying to mimic what Apple does in their quick alerts.

Please consider other libraries like [SwiftMessages](https://github.com/SwiftKickMobile/SwiftMessages) if your use case require custom UI.
