### ISSUE TITLE
Dark/Light mode control

### ISSUE THREAD

**Issue by vectorstofinal** [omaralbeik/Drops#37]
I prefer to have overlays like this show in the opposite color scheme than the current one in use - this is to make sure it stands out against the background of the normal app views.  So, feature request!

**Comment by omaralbeik** [comment]
Hi @vectorstofinal

This library was never intended to provide the most extensive way for showing alerts! we're trying to mimic what Apple does in their quick alerts.

Please consider other libraries like [SwiftMessages](https://github.com/SwiftKickMobile/SwiftMessages) if your use case require custom UI.
