### ISSUE TITLE
Retain-Cycle in `WindowViewController`

### ISSUE THREAD

**Issue by omidgolparvar** [omaralbeik/Drops#43]
In `Presenter` we have this:

```swift
init(toast: Toast, delegate: AnimatorDelegate) {
    self.toast = toast
    self.view = ToastView.initialize(for: toast)
    self.viewController = .init(value: WindowViewController())
    self.animator = Animator(position: toast.position, delegate: delegate)
    self.context = AnimationContext(view: view, container: maskingView)
}
```

and `viewController` is `Weak<WindowViewController>`.
So using `self.viewController = .init(value: WindowViewController())`, object related to `WindowViewController()` SHOULD release from memory immediately, because it declared `weak` and there is no strong-referece to it, but it will not. Why? Because of this:

```swift
final class WindowViewController: UIViewController {
	
    var window: UIWindow?
    
    // ...
	
    init() {
        let view = PassthroughView()
        let window = PassthroughWindow(hitTestView: view)
        self.window = window
        super.init(nibName: nil, bundle: nil)
        self.view = view
        window.rootViewController = self
    }

    // ...	
}
```
This `init` is creating Retain-Cycle, because `WindowViewController` has a strong-reference to `window`, and `window` has a strong-reference to `WindowViewController` by `window.rootViewController = self`.

So I think whenever we present a Toase, we are creating a `UIWindow` that will never be released.

**Comment by omaralbeik** [comment]
Hey @omidgolparvar
Sorry for my late response here
I don't see multiple `UIWindow` instances when instrumenting in Xcode, keep in mind that [`window` is being nilled-out in the `uninstall` method in `WindowViewController`](https://github.com/omaralbeik/Drops/blob/f4eabe3e4e5da69e5205a69a5ddc0effd4a90519/Sources/WindowViewController.swift#L63)

**Comment by omidgolparvar** [comment]
Hey @omaralbeik 
I checked it using code below, and you're right.
Thank you. ✌️

```swift
final class WindowViewController: UIViewController {
	
    deinit {
        print("WindowViewController.Deinit")
    }
    
    ...
}
```
