### ISSUE TITLE
Tapping Drop on iOS 17, built with Xcode 15, triggers EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by yumemi-ajike** [omaralbeik/Drops#45]
Hi,

EXC_BAD_ACCESS occurs when tapping 'Drop' in the [UIKitExample](https://github.com/omaralbeik/Drops/tree/main/UIKitExample) app built with [Xcode 15 RC](https://developer.apple.com/download/applications/), when running on iOS 17.

It seems to be accessing WindowController.preferredStatusBarStyle in an infinite loop.
Drop.action does not be firing.
This does not occur on iOS 16.

||
|-|
|<video width="600" src="https://github.com/omaralbeik/Drops/assets/33272228/dd1d97a0-81ff-4d31-8bc9-6e9aa0d780b0">|

Thanks for the great framework!

**Comment by yumemi-ajike** [comment]
I found the addition of a workaround for a UIKit bug in version [1.3.0](https://github.com/omaralbeik/Drops/releases/tag/1.3.0).
https://github.com/omaralbeik/Drops/pull/26/commits/6f0cd307523466f63102d0496dac24d8be75abf
Removing these lines can avoid the problem on iOS 17.

However, I don't know which version of iOS the workaround was implemented for, so I can't create an 'if' statement.

**Comment by mohakapt** [comment]
I just debugged it, looks like this line is returning the `WindowViewController` itself:
```
    let topViewController = windowScene?.windows.first(where: \.isKeyWindow)?.rootViewController?.top

    let check = topViewController == self // true
```

which is causing an infinite loop (StackOverflow) when trying to access the `preferredStatusBarStyle` on it:
```
    return topViewController?.preferredStatusBarStyle
      ?? windowScene?.statusBarManager?.statusBarStyle
      ?? .default
```

I wonder what's the goal of this code 🤔.
Judging form the [issue](https://github.com/omaralbeik/Drops/pull/22) linked in the code, it looks like the color of the status bar changes when the Drop appears. If that's the case I guess we should get the `preferredStatusBarStyle` from the view controller behind the one on top.
